FROM julia@sha256:09aba3b03f60dc888a571fb5796a7d1c62c93db515a4ac38f5a8fd5aab85baf3

WORKDIR /app

# Copy your Julia project files
COPY src/model_expansion /app/src/model_expansion

# Install dependencies
RUN julia --project=/app/src/model_expansion/. -e 'using Pkg; Pkg.instantiate()'

# Expose the port (documentation purposes)
ARG SERVER_JL_PORT=8000
EXPOSE ${SERVER_JL_PORT}

# The command will be overridden by docker-compose
CMD ["julia", "--project=/app/src/model_expansion/.", "/app/src/model_expansion/src/Server.jl", "${SERVER_JL_PORT}"]