{
 "title": "Serve LLM Dashboard",
 "tags": [ "rayVersion:2.48.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "vllm_model_name",
    "label": "vLLM Model Name",
    "query": {
     "query": "label_values(ray_vllm:request_prompt_tokens_sum{}, model_name)"
    }
   },
   {
    "name": "ray_llm_model_id",
    "label": "Ray LLM Model ID",
    "query": {
     "query": "label_values(ray_serve_llm_tokens_input_total{}, model_id)"
    }
   },
   {
    "name": "workerid",
    "label": "Worker ID",
    "query": {
     "query": "label_values(ray_serve_llm_tokens_input_total{}, WorkerId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "vLLM: Token Throughput",
   "type": "graph",
   "description": "Number of tokens processed per second",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "tokens/s" }
   ],
   "targets": [
    {
     "expr": "rate(ray_vllm:request_prompt_tokens_sum{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "Prompt Tokens/Sec"
    },
    {
     "expr": "rate(ray_vllm:generation_tokens_total{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "Generation Tokens/Sec"
    }
   ]
  },
  {
   "title": "vLLM: Time Per Output Token Latency",
   "type": "graph",
   "description": "Time per output token latency in seconds.",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "tokens" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ray_vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ray_vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(ray_vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ray_vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(ray_vllm:time_per_output_token_seconds_sum{model_name=~\"$vllm_model_name\", }[5m])\n/\nrate(ray_vllm:time_per_output_token_seconds_count{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "vLLM: Cache Utilization",
   "type": "graph",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "ray_vllm:gpu_cache_usage_perc{model_name=~\"$vllm_model_name\", }",
     "legendFormat": "GPU Cache Usage"
    },
    {
     "expr": "ray_vllm:cpu_cache_usage_perc{model_name=~\"$vllm_model_name\", }",
     "legendFormat": "CPU Cache Usage"
    }
   ]
  },
  {
   "title": "vLLM: Time To First Token Latency",
   "type": "graph",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ray_vllm:time_to_first_token_seconds_sum{model_name=~\"$vllm_model_name\", }[5m])\n/\nrate(ray_vllm:time_to_first_token_seconds_count{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le)(rate(ray_vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le)(rate(ray_vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ray_vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(ray_vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "vLLM: E2E Request Latency",
   "type": "graph",
   "description": "Latency from request start to first token returned (in seconds).",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ray_vllm:e2e_request_latency_seconds_sum{model_name=~\"$vllm_model_name\", }[5m])\n/\nrate(ray_vllm:e2e_request_latency_seconds_count{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ray_vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(ray_vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ray_vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ray_vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", }[5m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "vLLM: Scheduler State",
   "type": "graph",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "targets": [
    {
     "expr": "ray_vllm:num_requests_running{model_name=~\"$vllm_model_name\", }",
     "legendFormat": "Num Running"
    },
    {
     "expr": "ray_vllm:num_requests_swapped{model_name=~\"$vllm_model_name\", }",
     "legendFormat": "Num Swapped"
    },
    {
     "expr": "ray_vllm:num_requests_waiting{model_name=~\"$vllm_model_name\", }",
     "legendFormat": "Num Waiting"
    }
   ]
  },
  {
   "title": "vLLM: Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum by(le) (increase(ray_vllm:request_prompt_tokens_bucket{model_name=~\"$vllm_model_name\", }[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vLLM: Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum by(le) (increase(ray_vllm:request_generation_tokens_bucket{model_name=~\"$vllm_model_name\", }[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vLLM: Finish Reason",
   "type": "graph",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(ray_vllm:request_success_total{model_name=~\"$vllm_model_name\", }[5m]))",
     "legendFormat": "{{finished_reason}}"
    }
   ]
  },
  {
   "title": "vLLM: Queue Time",
   "type": "graph",
   "gridPos": { "x": 12, "y": 32, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ray_vllm:request_queue_time_seconds_sum{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "vLLM: Requests Prefill and Decode Time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 40, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ray_vllm:request_decode_time_seconds_sum{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "Decode"
    },
    {
     "expr": "rate(ray_vllm:request_prefill_time_seconds_sum{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "Prefill"
    }
   ]
  },
  {
   "title": "vLLM: Max Generation Token in Sequence Group",
   "type": "graph",
   "gridPos": { "x": 12, "y": 40, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ray_vllm:request_max_num_generation_tokens_sum{model_name=~\"$vllm_model_name\", }[5m])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 0, "y": 48, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Tokens" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_id) (delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\", model_id !~ \".+--.+\", }[1d])))",
     "legendFormat": "Input: {{model_id}}"
    },
    {
     "expr": "(sum by (model_id) (delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\", model_id !~ \".+--.+\", }[1d])))",
     "legendFormat": "Generated: {{model_id}}"
    }
   ]
  },
  {
   "title": "Tokens Last Hour",
   "type": "stat",
   "gridPos": { "x": 12, "y": 48, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Tokens" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\", }[1h])",
     "legendFormat": "Input: {{model_id}}"
    },
    {
     "expr": "delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\", }[1h])",
     "legendFormat": "Generated: {{model_id}}"
    }
   ]
  },
  {
   "title": "Requests Last Hour",
   "type": "graph",
   "gridPos": { "x": 0, "y": 56, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "targets": [
    {
     "expr": "(sum by (WorkerId) (delta(ray_serve_llm_requests_errored{WorkerId=~\"$workerid\", }[1h])))",
     "legendFormat": "Errored"
    },
    {
     "expr": "(sum by (WorkerId) (delta(ray_serve_llm_requests_finished{WorkerId=~\"$workerid\", }[1h])))",
     "legendFormat": "Finished"
    },
    {
     "expr": "(sum by (WorkerId) (delta(ray_serve_llm_requests_started{WorkerId=~\"$workerid\", }[1h])))",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Distribution of Requests Per Model Last 24 Hours",
   "type": "piechart",
   "gridPos": { "x": 12, "y": 56, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_requests_started{WorkerId=~\"$workerid\", model_id !~ \".+--.+\", }[1d]))",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "Ratio Input:Generated Tokens Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 0, "y": 64, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "none" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\", }[1d])) / sum by (model_id) (delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "Tokens Per Model Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 12, "y": 64, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Tokens" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\", }[1d])) + sum by (model_id) (delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "Peak Tokens Per Second Per Model Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 0, "y": 72, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Tokens/s" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (model_id) (rate(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\", }[2m]))[24h:])",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "Requests Per Model Last Week",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 72, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Requests" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_requests_started{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w]))",
     "legendFormat": "{{ model_id}}"
    }
   ]
  },
  {
   "title": "Avg Total Tokens Per Request Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 80, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Requests" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_id) (delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", model_id=~\"$ray_llm_model_id\", }[1w])) +\nsum by (model_id) (delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", model_id=~\"$ray_llm_model_id\", }[1w]))) / sum by (model_id) (delta(ray_serve_llm_requests_started{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", model_id=~\"$ray_llm_model_id\", }[1w]))",
     "legendFormat": "{{ model_id}}"
    }
   ]
  },
  {
   "title": "Avg Total Tokens Per Request Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 80, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Requests" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_id) (delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w])) + sum by (model_id) (delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w])))/ sum by (model_id) (delta(ray_serve_llm_requests_started{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w]))",
     "legendFormat": "{{ model_id}}"
    }
   ]
  },
  {
   "title": "Tokens Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 88, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Tokens" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w]))",
     "legendFormat": "In: {{ model_id}}"
    },
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w]))",
     "legendFormat": "Out: {{ model_id }}"
    }
   ]
  },
  {
   "title": "Tokens Per Request Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 88, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "Tokens" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_tokens_input{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w])) / sum by (model_id) (delta(ray_serve_llm_requests_started{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w]))",
     "legendFormat": "In: {{ model_id}}"
    },
    {
     "expr": "sum by (model_id) (delta(ray_serve_llm_tokens_generated{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w])) / sum by (model_id) (delta(ray_serve_llm_requests_started{WorkerId=~\"$workerid\",model_id !~ \".+--.+\", }[1w]))",
     "legendFormat": "Out: {{ model_id}}"
    }
   ]
  }
 ]
}